<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ZIL1280" failures="1" tests="3" name="Guest User - Plans Availability-0" time="161.785" errors="0" timestamp="2023-12-18T00:58:01 IST">
  <testcase classname="com.perficient.util.TestCaseBase" name="@AfterMethod afterMethod" time="0.156">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
at com.perficient.util.TestCaseBase.afterMethod(TestCaseBase.java:205)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase classname="com.perficient.util.TestCaseBase" name="@AfterMethod afterMethod" time="0.084">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
at com.perficient.util.TestCaseBase.afterMethod(TestCaseBase.java:205)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase classname="com.perficient.testCases.Desktop.purdy.Verify_Login_Page_with_valid_credentials" name="customerLogin" time="30.483"/>
  <testcase classname="com.perficient.testCases.Desktop.purdy.Verify_Login_Page_with_valid_credentials" name="redirectToLoginPage" time="16.31"/>
  <testcase classname="com.perficient.testCases.Desktop.purdy.Verify_Login_Page_with_valid_credentials" name="homePageValidationAfterLogin" time="97.349">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at com.perficient.util.TestMethodListener.afterInvocation(TestMethodListener.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- homePageValidationAfterLogin -->
</testsuite> <!-- Guest User - Plans Availability-0 -->
